### PR TITLE
Update the version specific tweeter.json.

### PR DESCRIPTION
**Pull request by joerg84**

### CODE REVIEW

**Comment by margaret** [comment]
👍 And for reference in case you make demos directories for newer versions, 1.10 and 1.11 work with the top-level app definition files. If we need to the change the files again for those or newer versions then we'll make new version directories for those. (top-level is expected to work with the master branches)

**Review by pleia2 — DISMISSED** [review]

**Comment by pleia2** [comment]
I think I need more background on this. I tested on 1.9 and get: ArgumentError: :hosts ["node-0.cassandra.mesos"] could not be resolved to any ip address

The address in the top level tweeter.json works fine, and that json file worked in my test on 1.9.4.

**Comment by joerg84** [comment]
@pleia2 This is due to the new Cassandra version changing its task name to  `node-0-server`. I will fix the cassandra installed for 1.9 to a pre-SDK one. For the the 1.10 demo we then need to use the new DNS entry.

**Comment by joerg84** [comment]
We are just discussing what is the better 
Update the 1.9 json file or fix the cassandra version

**Review by pleia2 — COMMENTED** [review]
The JSON file now works.

However, on line 95 we're still making a reference to node-0.cassandra.mesos:9042 and on line 105 we're using the top-level post-tweets.json, which works but there is a 1.9 specific one now, do we want to use that? Same goes for references to tweeter-analytics.json, there's now a 1.9 version.

**Comment by yankcrime** [comment]
Closing this as a stale PR.

**Pull request closed without merging**
